fix

diff --git a/main b/main
--- a/main
+++ b/main
@@ -2,6 +2,8 @@
 
 ORIGINAL_PWD=$(pwd)
 
+echo -ne "\033]30;OmniOpt\007"
+
 set -e
 set -o pipefail
 
@@ -10,12 +12,6 @@ function mycd () {
 	cd $1
 }
 
-function calltracer () {
-        echo 'Last file/last line:'
-        caller
-}
-
-trap 'calltracer' ERR
 
 slurmlogpath () {
 	if command -v scontrol 2>/dev/null >/dev/null; then
@@ -38,6 +34,16 @@ function green_text {
 function red_text {
 	echoerr -e "\e[31m$1\e[0m"
 }
+
+function calltracer () {
+	echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
+	yellow_text "Git status hash:"
+	git rev-parse HEAD
+        red_text 'Error occured in file/line:'
+        caller
+}
+
+trap 'calltracer' ERR
 
 minutes_to_hh_mm_ss() {
 	var=$1
@@ -63,14 +69,16 @@ minutes_to_hh_mm_ss() {
 
 int_re='^[+-]?[0-9]+$'
 
-export mem_gb=
-export gpus=
-export time=
-export experiment_name=
-export help=0
-export follow=0
-export debug=0
-export wait_until_ended=0
+continue_previous_job=""
+mem_gb=
+gpus=
+time=
+experiment_name=
+help=0
+follow=0
+debug=0
+wait_until_ended=0
+tests=0
 
 args_string=""
 
@@ -80,6 +88,73 @@ while [ $k -lt ${#args[@]} ]; do
 	i="${args[k]}"
 
 	case $i in
+		--continue=*)
+			old_continue=$continue_previous_job
+			continue_previous_job="${i#*=}"
+
+			if [[ ! -z $old_continue ]]; then
+				red_text "--continue was specified more than once. Using the last one."
+				args_string=$(echo "$args_string" | sed -e 's#\s*--continue=.*\s\s*# #')
+			fi
+
+			args_string+=" --continue $continue_previous_job "
+
+			continue_previous_job=$continue_previous_job
+
+			;;
+		--continue)
+			old_continue=$continue_previous_job
+
+			shift
+			k=$((k+1))
+
+			continue_previous_job="${args[k]}"
+
+			if [[ ! -z $old_continue ]]; then
+				red_text "--continue was specified more than once. Using the last one."
+				args_string=$(echo "$args_string" | sed -e 's#\s*--continue=.*\s\s*# #')
+			fi
+
+			args_string+=" --continue $continue_previous_job "
+
+			continue_previous_job=$continue_previous_job
+
+			;;
+
+		--continue_previous_job=*)
+			old_continue=$continue_previous_job
+			continue_previous_job="${i#*=}"
+
+			if [[ ! -z $old_continue ]]; then
+				red_text "--continue was specified more than once. Using the last one."
+				args_string=$(echo "$args_string" | sed -e 's#\s*--continue=.*\s\s*# #')
+			fi
+
+			args_string+=" --continue $continue_previous_job "
+
+			continue_previous_job=$continue_previous_job
+
+			;;
+
+		--continue_previous_job)
+			old_continue=$continue_previous_job
+
+			shift
+			k=$((k+1))
+
+			continue_previous_job="${args[k]}"
+
+			if [[ ! -z $old_continue ]]; then
+				red_text "--continue was specified more than once. Using the last one."
+				args_string=$(echo "$args_string" | sed -e 's#\s*--continue.*\s\s*# #')
+			fi
+
+			args_string+=" --continue $continue_previous_job "
+
+			continue_previous_job=$continue_previous_job
+
+			;;
+
 		--mem_gb=*)
 			old_mem_gb=$mem_gb
 			mem_gb="${i#*=}"
@@ -212,6 +287,10 @@ while [ $k -lt ${#args[@]} ]; do
 
 			;;
 
+		--tests)
+			tests=1
+			;;
+
 		--follow)
 			follow=1
 			;;
@@ -281,20 +360,53 @@ if [[ -z $gpus ]]; then
 	gpus=0
 fi
 
-if [[ $help -eq 0 ]] && command -v sbatch >/dev/null; then
+if [[ $tests -eq 0 ]]; then
+	if [[ $help -eq 0 ]] && command -v sbatch >/dev/null; then
+		if [[ "$continue_previous_job" == "" ]]; then
+			if [[ -z "$mem_gb" ]]; then
+				red_text "Parameter --mem_gb is missing or empty";
+				exit 101
+			fi
+
+			if [[ -z "$time" ]]; then
+				red_text "Parameter --time is missing or empty";
+				exit 102
+			fi
+
+			if [[ -z $experiment_name ]]; then
+				red_text "Parameter --experiment_name is missing or empty"
+				exit 104
+			fi
+		fi
+	fi
+fi
+
+if [[ "$continue_previous_job" != "" ]]; then
 	if [[ -z "$mem_gb" ]]; then
-		red_text "Parameter --mem_gb is missing or empty";
-		exit 101
+		if [[ -e "$continue_previous_job/mem_gb" ]]; then
+			mem_gb=$(cat "$continue_previous_job/mem_gb")
+		else
+			echo "mem_gb could not be determined from previous run or --mem_gb"
+			exit 105
+		fi
+	fi
+
+	if [[ -z "$gpus" ]]; then
+		if [[ -e "$continue_previous_job/gpus" ]]; then
+			gpus=$(cat "$continue_previous_job/gpus")
+		else
+			echo "gpus could not be determined from previous run or --gpus"
+			exit 105
+		fi
 	fi
 
 	if [[ -z "$time" ]]; then
-		red_text "Parameter --time is missing or empty";
-		exit 102
-	fi
-
-	if [[ -z $experiment_name ]]; then
-		red_text "Parameter --experiment_name is missing or empty"
-		exit 104
+		if [[ -e "$continue_previous_job/time" ]]; then
+			time=$(cat "$continue_previous_job/time")
+		else
+			echo "Time could not be determined from previous run or --time"
+			exit 105
+		fi
 	fi
 fi
 
@@ -326,8 +438,10 @@ run_before_end () {
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
 if [ -n "${SLURM_JOB_ID:-}" ] ; then
+	set +e
 	SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
 	SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
+	set -e
 
 	if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
 		SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
@@ -348,6 +462,31 @@ if [[ "$help" -eq "1" ]]; then
 	python3 $SCRIPT_DIR/.main.py --help
 	exit 0
 fi
+
+if [[ "$tests" -eq "1" ]]; then
+	python3 $SCRIPT_DIR/.main.py --tests --num_parallel_jobs=1 --max_eval=1 --worker_timeout=1 --run_program "" --experiment_name ""
+	exit $?
+fi
+
+kill_tail_when_squeue_job_empty () {
+	JOB_ID=$1
+
+	sleep 10
+
+	while squeue -u $USER | grep "$JOB_ID" 2>/dev/null >/dev/null; do
+		sleep 5
+	done
+
+	sleep 10
+
+	for child in $(pgrep -P $$); do
+		for tail_process in $(ps auxf | grep $child | grep tail | sed -e "s#^$USER\s*##" -e 's#\s.*##'); do
+			kill -9 $tail_process
+		done
+	done
+
+	return 0
+}
 
 if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
 	# To start all subjobs indenpedently from the main job, unset all SLURM variables
@@ -370,7 +509,9 @@ if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
 
 	run_before_end &
 
+	set +e
 	python3 $SCRIPT_DIR/.main.py $args_string
+	set -e
 
 	EXIT_CODE=$?
 
@@ -386,10 +527,10 @@ else
 	exit_code=""
 
 	if [[ $gpus -ne 0 ]]; then
-		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB --gres=gpu:$gpus $SCRIPT_DIR/main $* | tee /dev/stderr)
+		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB --gres=gpu:$gpus $SCRIPT_DIR/main $args_string | tee /dev/stderr)
 		exit_code=$?
 	else
-		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB $SCRIPT_DIR/main $* | tee /dev/stderr)
+		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB $SCRIPT_DIR/main $args_string | tee /dev/stderr)
 		exit_code=$?
 	fi
 
@@ -401,7 +542,7 @@ else
 				LOG_PATH=$(slurmlogpath $started_job_nr)
 	
 				spin[0]="-"
-				spin[1]="\\"
+				spin[1]="\\" # "
 				spin[2]="|"
 				spin[3]="/"
 
@@ -424,36 +565,61 @@ else
 
 				tput el
 
-				tail -n1000000 -f $LOG_PATH
+				if [[ -e "$LOG_PATH" ]]; then
+					set +x
+					kill_tail_when_squeue_job_empty $started_job_nr &
+					# weird exec stuff for disabling the "Terminated" message coming from kill
+					exec 3>&2          # 3 is now a copy of 2
+					exec 2> /dev/null  # 2 now points to /dev/null
+					tail -n1000000 -f $LOG_PATH || true
+					exec 2>&3          # restore stderr to saved
+					exec 3>&-          # close saved version
+					if [[ "$debug" -eq "1" ]]; then
+						set -x
+					fi
+				else
+					red_text "$LOG_PATH could not be found"
+				fi
+			fi
+		elif [[ "$wait_until_ended" -eq "1" ]]; then
+			if command -v squeue 2>/dev/null >/dev/null; then
+				WAIT_NUM_SECONDS=10
+				yellow_text "Waiting for job $started_job_nr to end... (Checking every $WAIT_NUM_SECONDS seconds)"
+
+				set +x
+
+				seconds_count=0
+
+				echo ""
+
+				while [[ "$(squeue --me | grep $started_job_nr | wc -l)" -ne "0" ]]; do
+					sleep $WAIT_NUM_SECONDS
+				done
+
+				echo ""
+
+				if [[ "$debug" -eq 1 ]]; then
+					set -x
+				fi
+
+				yellow_text "Done waiting for job to end"
+
+				LOG_PATH=$(slurmlogpath $started_job_nr)
+				if [[ -e "$LOG_PATH" ]]; then
+					cat $LOG_PATH
+				else
+					red_text "$LOG_PATH could not be found"
+				fi
+			else
+				red_text "squeue not found. Cannot wait for job to end."
 			fi
 		fi
 	else
 		red_text "Failed to start sbatch job. Exit-Code: $exit_code"
+
+		exit $exit_code
 	fi
 
-	if [[ "$wait_until_ended" -eq "1" ]]; then
-		if command -v squeue 2>/dev/null >/dev/null; then
-			yellow_text "Waiting for job $started_job_nr to end... (Checking every 10 seconds)"
-
-			set +x
-
-			seconds_count=0
-
-			echo ""
-
-			while [[ "$(squeue --me | grep $started_job_nr | wc -l)" -ne "0" ]]; do
-				sleep 10
-			done
-
-			echo ""
-
-			if [[ "$debug" -eq 1 ]]; then
-				set -x
-			fi
-
-			yellow_text "Done waiting for job to be ended"
-		else
-			red_text "squeue not found. Cannot wait for job to end."
-		fi
-	fi
 fi
+
+echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
