new version

diff --git a/omniopt b/omniopt
--- a/omniopt
+++ b/omniopt
@@ -1,5 +1,31 @@
 #!/bin/bash
 
+# Idea for how this works and is implemented technically:
+# This main script that is supposed to be called is a bash script.
+# Step 1:
+# , it checks whether the environment already exists, and
+# if so, loads it.
+# If it doesn't exist. it creates it in 
+# ~/.omniax_$(uname -m)
+# i.e. e.g. ~/.omniax__x86_64.
+# Then it installs all modules. Then it loads the environment and the job
+# continues.
+# These steps are skipped, when you installed it as a module. Then,
+# the module environment is the used environment.
+# This logic is defined in .shellscript_functions
+# Step 2:
+# It checks whether sbatch is installed. If so, it will re-start
+# itself as a bascript in a slurmjob.
+# If not, the python-script with the parsed parameters are run directly.
+# Otherwise, the python-script is started inside the sbatch-script,
+# which's end is awaited (by checking squeue every 10 seconds in the
+# background if the started job is still there, and, if --follow is
+# defined, a tail -f on the slurm.out file is loaded in the foreground).
+# This way, the whole slurm procedure is transparent to the user,
+# and the program looks basically the same on every device.
+
+export NO_WHIPTAIL=1
+
 function displaytime {
 	local T=$1
 		local D=$((T/60/60/24))
@@ -17,8 +43,6 @@ function displaytime {
 
 export CUDA_DEVICE_ORDER=PCI_BUS_ID
 export ORIGINAL_PWD=$(pwd)
-
-echo -ne "\033]30;OmniOpt\007"
 
 set -e
 set -o pipefail
@@ -52,16 +76,13 @@ function red_text {
 }
 
 function calltracer () {
-	echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
 	yellow_text "Git status hash:"
 	git rev-parse HEAD
         red_text 'Error occured in file/line:'
         caller
 
 	echo "Runtime: $(displaytime $SECONDS)"
-	echo -ne "\033]30;OmniOpt: Failed\007"
 	tput bel
-	echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
 }
 
 already_sent_signal=
@@ -85,9 +106,7 @@ kill_python_if_started () {
 	fi
 
 	echo "Runtime: $(displaytime $SECONDS)"
-	echo -ne "\033]30;OmniOpt: Failed\007"
 	tput bel
-	echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
 }
 
 trap 'calltracer' ERR
@@ -386,7 +405,10 @@ if [[ "$debug" -eq "1" ]]; then
 	set -x
 fi
 
-echo "Current git-hash: $(git rev-parse HEAD)"
+
+if [[ -z "$SLURM_JOB_ID" ]]; then
+	echo "Current git-hash: $(git rev-parse HEAD)"
+fi
 
 set +x
 if [[ -d ".git" ]]; then
@@ -503,14 +525,19 @@ SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
 if [ -n "${SLURM_JOB_ID:-}" ] ; then
 	set +e
-	SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
-	SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
-	set -e
+	if command -v scontrol 2>/dev/null >/dev/null; then
+		SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
+		SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
+		set -e
 
-	if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
-		SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
+		if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
+			SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
+		else
+			echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
+		fi
 	else
-		echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
+		red_text "scontrol not found. Unsetting SLURM_JOB_ID"
+		unset SLURM_JOB_ID
 	fi
 fi
 
@@ -582,10 +609,7 @@ if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
 	set -e
 
 	if [[ "$EXIT_CODE" -ne "0" ]]; then
-		echo -ne "\033]30;OmniOpt: Failed\007"
 		echo "Exiting with exit-code $EXIT_CODE"
-	else
-		echo -ne "\033]30;OmniOpt: done\007"
 	fi
 
 	tput bel
@@ -650,6 +674,8 @@ else
 					if [[ "$debug" -eq "1" ]]; then
 						set -x
 					fi
+
+					exit_code=$(cat $LOG_PATH | grep -i "exit-code" | sed -e 's#Exit-Code:\s*##i')
 				else
 					red_text "$LOG_PATH could not be found"
 				fi
@@ -696,4 +722,4 @@ else
 fi
 
 echo "Runtime: $(displaytime $SECONDS)"
-echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
+exit $exit_code
diff --git a/omniopt_plot b/omniopt_plot
--- a/omniopt_plot
+++ b/omniopt_plot
@@ -1,8 +1,81 @@
 #!/bin/bash
 
+_save_to_file=0
+
+function inputbox {
+	TITLE=$1
+	MSG=$2
+	DEFAULT=$3
+
+	eval `resize`
+	RESULT=$(whiptail --inputbox "$MSG" $LINES $COLUMNS "$DEFAULT" --title "$TITLE" 3>&1 1>&2 2>&3)
+	exitstatus=$?
+	if [[ $exitstatus == 0 ]]; then
+		echo "$RESULT"
+	else
+		echo "You chose to cancel (1)"
+		exit 1
+	fi
+}
+
+function ask_min_max {
+	min=$(inputbox "Minimum value for plot" "Enter a Minimum value for plotting $run_dir (float), leave empty for no Minimum value" "")
+	max=$(inputbox "Maximum value for plot" "Enter a Maximum value for plotting $run_dir (float), leave empty for no Maximum value" "")
+
+	if [ -n "$min" ]; then
+		# Check if $min is a number (integer or float, positive or negative)
+		if [[ ! "$min" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
+			echo "\$min is not a valid number. Setting it to empty."
+			min=""
+		fi
+	fi
+
+
+	if [ -n "$max" ]; then
+		# Check if $max is a number (integer or float, positive or negative)
+		if [[ ! "$max" =~ ^-?[0-9]+(\.[0-9]+)?$ ]]; then
+			echo "\$max is not a valid number. Setting it to empty."
+			max=""
+		fi
+	fi
+
+	if [ -n "$min" ] && [ -n "$max" ]; then
+		# Check if min is greater than max
+		if (( $(echo "$max < $min" |bc -l) )); then
+			# Swap values
+			temp="$min"
+			min="$max"
+			max="$temp"
+		else
+			echo "min is less than or equal to max. No need to swap."
+			true
+		fi
+	fi
+}
+
+
+function displaytime {
+	local T=$1
+	local D=$((T/60/60/24))
+	local H=$((T/60/60%24))
+	local M=$((T/60%60))
+	local S=$((T%60))
+	(( $D > 0 )) && printf '%d days ' $D
+	(( $H > 0 )) && printf '%d hours ' $H
+	(( $M > 0 )) && printf '%d minutes ' $M
+	(( $D > 0 || $H > 0 || $M > 0 )) && printf 'and '
+	printf '%d seconds\n' $S
+}
+
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 export ORIGINAL_PWD=$(pwd)
 
-echo -ne "\033]30;OmniOpt: plot\007"
+expected_plot_types=("default")
+whiptail_args=()
+
+for possible_plot_type in $(ls $SCRIPT_DIR/.omniopt_plot_*.py | sed -e 's#\.py##' -e 's#.*_plot_##'); do
+	expected_plot_types+=("$possible_plot_type")
+done
 
 function echoerr() {
         echo "$@" 1>&2
@@ -20,35 +93,219 @@ function calltracer () {
         caller
 
 	echo "Runtime: $(displaytime $SECONDS)"
-	echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
 }
 trap 'calltracer' ERR
+
+plot_type="default"
+min=
+max=
+run_dir=""
 help=0
 
-for i in $@; do
-        case $i in
+args=($*)
+k=0
+while [ $k -lt ${#args[@]} ]; do
+	arg="${args[k]}"
+
+        case $arg in
+		--run_dir=*)
+			run_dir="${arg#*=}"
+			shift
+			;;
+
+		--run_dir)
+			k=$((k+1))
+
+			run_dir="${args[k]}"
+
+			shift
+			shift
+			;;
+
+
+
+		--min=*)
+			min="${arg#*=}"
+			shift
+			;;
+		--min)
+			k=$((k+1))
+
+			min="${args[k]}"
+			shift
+			;;
+		--max=*)
+			max="${arg#*=}"
+			shift
+			;;
+		--max)
+			k=$((k+1))
+
+			max="${args[k]}"
+			shift
+			;;
+		--plot_type=*)
+			plot_type="${arg#*=}"
+			shift
+			;;
+		--plot_type)
+			k=$((k+1))
+
+			plot_type="${args[k]}"
+			shift
+			;;
                 --help|-h)
 			help=1
+			shift
                         ;;
                 --debug)
                         set -x
                         ;;
         esac
+	k=$((k+1))
 done
 
+if [[ ! " ${expected_plot_types[@]} " =~ " $plot_type " ]]; then
+    echo "Wrong plot type: $plot_type, but got $plot_type"
+fi
 
-#SBATCH --signal=B:USR1@120
+if [[ "$plot_type" == "default" ]]; then
+	if [[ "$run_dir" == "" ]]; then
+		echo "--run_dir is missing"
+		exit 1
+	fi
 
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+	if [[ -f "$run_dir" ]]; then
+		echo "--run_dir is a file"
+		exit 1
+	fi
 
-if [ -n "${SLURM_JOB_ID:-}" ] ; then
-	SLURM_FILE_SCRIPT_DIR=$(scontrol show job "$SLURM_JOB_ID" | awk -F= '/Command=/{print $2}')
-	SLURM_FILE_SCRIPT_DIR=$(dirname $SLURM_FILE_SCRIPT_DIR)
+	if [[ ! -d "$run_dir" ]]; then
+		echo "--run_dir is not a directory"
+		exit 1
+	fi
 
-	if [[ -d $SLURM_FILE_SCRIPT_DIR ]]; then
-		SCRIPT_DIR="$SLURM_FILE_SCRIPT_DIR"
+	eval `resize`
+
+	for possible_plot_type in "${expected_plot_types[@]}"; do
+		if [[ "$possible_plot_type" == "default" ]]; then
+			continue
+		fi
+
+		expected_files=()
+		for expected_file in $(cat $SCRIPT_DIR/.omniopt_plot_${possible_plot_type}.py | grep "# EXPECTED FILES" | sed -e 's/# EXPECTED FILES: //'); do
+			expected_files+=("$expected_file")
+		done
+
+		ALL_FILES_THERE=1
+
+		for expected_file in "${expected_files[@]}"; do
+			if [[ $(ls $run_dir | grep "$expected_file" | wc -l 2>/dev/null) -lt 1 ]]; then
+				ALL_FILES_THERE=0
+			fi
+		done
+
+		if [[ $ALL_FILES_THERE -eq 1 ]]; then
+			trap '' ERR
+			set +e
+			num_not_disabled_min_param=$(grep args.min $SCRIPT_DIR/.omniopt_plot_${possible_plot_type}.py | wc -l)
+			set -e
+			trap 'calltracer' ERR
+
+			accepts_min_max_string=""
+
+			if [[ "$num_not_disabled_min_param" -ne "0" ]]; then
+				accepts_min_max_string=", honours min/max"
+			fi
+
+			whiptail_args+=("$possible_plot_type" "$(cat $SCRIPT_DIR/.omniopt_plot_${possible_plot_type}.py | grep '# DESCRIPTION' | sed -e 's/#\s*DESCRIPTION: //')$accepts_min_max_string")
+			if grep add_argument $SCRIPT_DIR/.omniopt_plot_${possible_plot_type}.py | grep save_to_file | grep -v useless 2>&1 >/dev/null; then
+				whiptail_args+=("$possible_plot_type --save_to_file" "$(cat $SCRIPT_DIR/.omniopt_plot_${possible_plot_type}.py | grep '# DESCRIPTION' | sed -e 's/#\s*DESCRIPTION: //')$accepts_min_max_string")
+			fi
+		fi
+	done
+
+	if [ ${#whiptail_args[@]} -eq 0 ]; then
+		echo "It seems like the run folder does not have any plottable data."
+		exit 3
+	fi
+
+	minmaxstring=""
+	if [[ -z $min ]] && [[ -z $max ]]; then
+		#minmaxstring="Neither min nor max were set"
+		true
+	elif [[ -z $min ]] && ! [[ -z $max ]]; then 
+		minmaxstring=" (max: $max)"
+	elif ! [[ -z $min ]] && [[ -z $max ]]; then 
+		minmaxstring=" (min: $min)"
 	else
-		echo "SLURM_FILE_SCRIPT_DIR $SLURM_FILE_SCRIPT_DIR not found, even though SLURM_JOB_ID exists ($SLURM_JOB_ID). Using SCRIPT_DIR=$SCRIPT_DIR"
+		minmaxstring=" (min: $min, max: $max)"
+	fi
+
+	if [[ -z $min ]] && [[ -z $max ]]; then
+		#minmaxstring="Neither min nor max were set"
+		true
+	elif [[ -z $min ]] && ! [[ -z $max ]]; then 
+		minmaxstring="(max: $max)"
+	elif ! [[ -z $min ]] && [[ -z $max ]]; then 
+		minmaxstring=" (min: $min)"
+	else
+		minmaxstring=" (min: $min, max: $max)"
+	fi
+
+	WHATTODO=$(whiptail \
+		--title "Available options for $run_dir" \
+		--menu \
+		"Chose what plot to open:" \
+		$LINES $COLUMNS $(( $LINES - 8 )) \
+		"minmax)" "set min/max values$minmaxstring" \
+		"${whiptail_args[@]}" \
+		"q)" "quit" 3>&1 1>&2 2>&3
+	)
+
+	if [[ "$WHATTODO" == "q)" ]]; then
+		exit 0
+	fi
+
+	if [[ "$WHATTODO" == "minmax)" ]]; then
+		ask_min_max
+
+		if [[ -z $min ]] && [[ -z $max ]]; then
+			#echo "Neither min nor max were set"
+			bash $SCRIPT_DIR/omniopt_plot --run_dir $run_dir $*
+		elif [[ -z $min ]] && ! [[ -z $max ]]; then 
+			echo "min was not set but max ($max)"
+			bash $SCRIPT_DIR/omniopt_plot --run_dir $run_dir $* --max=$max 
+			exit $?
+		elif ! [[ -z $min ]] && [[ -z $max ]]; then 
+			echo "min ($min) was set but max was not"
+			bash $SCRIPT_DIR/omniopt_plot --run_dir $run_dir $* --min=$min 
+			exit $?
+		else
+			echo "min ($min) and max ($max) were set"
+			bash $SCRIPT_DIR/omniopt_plot --run_dir $run_dir $* --max=$min -max=$max 
+			exit $?
+		fi
+
+		echo "This exit should never be reached"
+		exit
+	fi
+
+	plot_type=$WHATTODO
+	if [[ "$plot_type" == *"save_to_file"* ]]; then
+		plot_type=$(echo "$plot_type" | sed -e 's# .*##')
+		_save_to_file=1
+	fi
+
+	if [[ "$_save_to_file" == "1" ]]; then
+		_path=$(whiptail --inputbox "Path of the plot?" 8 39 "$run_dir/$plot_type.svg" --title "Choose path" 3>&1 1>&2 2>&3)
+
+		exitstatus=$?
+		if [ $exitstatus = 0 ]; then
+			_save_to_file="$_path"
+		else
+			exit 0
+		fi
 	fi
 fi
 
@@ -57,14 +314,36 @@ cd $ORIGINAL_PWD
 source $SCRIPT_DIR/.shellscript_functions
 source $SCRIPT_DIR/.general.sh
 
-set +e
-OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot.py $* 2>&1)
-exit_code=$?
-set -e
+if [[ "$plot_type" != "default" ]]; then
+	if ! [[ -e "$SCRIPT_DIR/.omniopt_plot_$plot_type.py" ]]; then
+		# Verbinden Sie die Elemente des Arrays zu einem mit "," getrennten String
+		joined_plot_types=$(printf "%s, " "${expected_plot_types[@]}")
+
+		# Entfernen Sie das letzte "," vom gejointen String
+		joined_plot_types=${joined_plot_types%, }
+
+		echo "Invalid plot type $plot_type, valid plot types: $joined_plot_types"
+		exit 5
+	fi
+fi
+
+set +ex
+if [[ "$_save_to_file" == "0" ]]; then
+	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot_$plot_type.py --run_dir $run_dir $* 2>&1)
+	exit_code=$?
+else
+	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot_$plot_type.py --run_dir $run_dir --save_to_file $_save_to_file $* 2>&1)
+	exit_code=$?
+fi
+set -ex
 
 if [[ "$exit_code" -ne "0" ]]; then
 	if command -v whiptail 2>/dev/null >/dev/null; then
-		error_message "$OUTPUT"
+		if [[ -z $NO_WHIPTAIL ]]; then
+			error_message "$OUTPUT"
+		else
+			echo $OUTPUT
+		fi
 	else
 		echo -- "$OUTPUT"
 	fi
@@ -73,4 +352,4 @@ else
 fi
 
 echo "Runtime: $(displaytime $SECONDS)"
-echo -ne "\033]30;$(basename $(pwd)): $(basename $SHELL)\007"
+exit $exit_code
