new version

diff --git a/.tests/optimization_example b/.tests/optimization_example
--- a/.tests/optimization_example
+++ b/.tests/optimization_example
@@ -23,6 +23,7 @@ function help () {
         echo "  --int_param_two=(INT)"
         echo "  --float_param=(FLOAT)"
         echo "  --choice_param=(STRING)                            Must be 1, 2, 4, 8, 16 or hallo"
+        echo "  --fail_or_not=0|1                                         Whether to fail or not"
         echo "  --help                                             this help"
         echo "  --debug                                            Enables debug mode (set -x)"
         exit $1
@@ -31,37 +32,31 @@ export int_param=
 export int_param_two=
 export float_param=
 export choice_param=
+export fail_or_not=0
+
 for i in $@; do
         case $i in
                 --int_param_two=*)
                         int_param_two="${i#*=}"
-                        re='^[+-]?[0-9]+$'
-                        if ! [[ $int_param_two =~ $re ]] ; then
-                                red_text "error: Not a INT: $i" >&2
-                                help 1
-                        fi
                         shift
                         ;;
                 --int_param=*)
                         int_param="${i#*=}"
-                        re='^[+-]?[0-9]+$'
-                        if ! [[ $int_param =~ $re ]] ; then
-                                red_text "error: Not a INT: $i" >&2
-                                help 1
-                        fi
                         shift
                         ;;
                 --float_param=*)
                         float_param="${i#*=}"
-                        re='^[+-]?[0-9]+([.][0-9]+)?$'
-                        if ! [[ $float_param =~ $re ]] ; then
-                                red_text "error: Not a FLOAT: $i" >&2
-                                help 1
-                        fi
                         shift
                         ;;
                 --choice_param=*)
                         choice_param="${i#*=}"
+                        shift
+                        ;;
+                --fail_or_not=*)
+                        new_param="${i#*=}"
+			if [[ "$new_param" == *"1"* ]]; then
+				fail_or_not=1
+			fi
                         shift
                         ;;
                 -h|--help)
@@ -81,6 +76,10 @@ if [[ -z "$int_param" ]]; then red_text "Parameter --int_param cannot be empty";
 if [[ -z "$int_param_two" ]]; then red_text "Parameter --int_param_two cannot be empty"; help 1; fi
 if [[ -z "$float_param" ]]; then red_text "Parameter --float_param cannot be empty"; help 1; fi
 if [[ -z "$choice_param" ]]; then red_text "Parameter --choice_param cannot be empty"; help 1; fi
+
+if [[ "$fail_or_not" -eq "1" ]]; then
+	exit 1
+fi
 
 case $choice_param in
     1|2|4|8|16|hallo)
diff --git a/omniopt b/omniopt
--- a/omniopt
+++ b/omniopt
@@ -3,16 +3,19 @@
 # Idea for how this works and is implemented technically:
 # This main script that is supposed to be called is a bash script.
 # Step 1:
-# , it checks whether the environment already exists, and
+# It checks whether the environment already exists, and
 # if so, loads it.
 # If it doesn't exist. it creates it in 
-# ~/.omniax_$(uname -m)
-# i.e. e.g. ~/.omniax__x86_64.
+# ~/.omniax_$(uname -m)_$(python3 --version | sed -e 's# #_#g')
+# i.e. e.g. ~/.omniax_x86_64_Python_3.11.2/ . This is done so that there
+# is no need for multiple installations, so that, once installed, it doesn't 
+# need to be installed again.
 # Then it installs all modules. Then it loads the environment and the job
-# continues.
+# continues. It also does pip freeze to check if new modules need to be
+# installed and if the environment already exists, but the new modules are 
+# missing, they will be installed automatically.
 # These steps are skipped, when you installed it as a module. Then,
 # the module environment is the used environment.
-# This logic is defined in .shellscript_functions
 # Step 2:
 # It checks whether sbatch is installed. If so, it will re-start
 # itself as a bascript in a slurmjob.
@@ -23,10 +26,18 @@
 # defined, a tail -f on the slurm.out file is loaded in the foreground).
 # This way, the whole slurm procedure is transparent to the user,
 # and the program looks basically the same on every device.
+# This logic is defined in .shellscript_functions
+
+if [[ ! -z $PRINT_SEPERATOR ]]; then # for tests, so that things are properly visually seperated
+	echo ""
+	echo "========================================================================"
+	echo ""
+fi
 
 export NO_WHIPTAIL=1
 
 function displaytime {
+	set +x
 	local T=$1
 		local D=$((T/60/60/24))
 		local H=$((T/60/60%24))
@@ -37,6 +48,88 @@ function displaytime {
 		(( $M > 0 )) && printf '%d minutes ' $M
 		(( $D > 0 || $H > 0 || $M > 0 )) && printf 'and '
 		printf '%d seconds\n' $S
+}
+
+function remaining_time {
+	target_date="$1"
+	target_date=$(echo "$target_date" | sed -E 's/\x1b\[[0-9;]*m//g')
+
+	target_epoch=$(date -d "$target_date" +%s)
+
+	current_epoch=$(date +%s)
+
+	difference=$(( target_epoch - current_epoch ))
+
+	if [ $difference -lt 0 ]; then
+		return
+	fi
+
+	difference_minutes=$(( difference / 60 ))
+
+	if [ $difference_minutes -lt 30 ]; then
+		minutes=$difference_minutes
+		if [ $minutes -eq 1 ]; then
+			result="in about $minutes minute"
+		else
+			result="in about $minutes minutes"
+		fi
+		echo "$result"
+		return
+	fi
+
+	difference_rounded=$(( (difference + 299) / 300 * 5 ))
+
+	minutes=$(( difference_rounded % 60 ))
+	hours=$(( (difference_rounded / 60) % 24 ))
+	days=$(( (difference_rounded / 1440) % 365 ))
+	years=$(( difference_rounded / 525600 ))
+
+	result=""
+	if [ $years -gt 0 ]; then
+		year_str="year"
+		if [ $years -gt 1 ]; then
+			year_str="years"
+		fi
+		result="$result $years $year_str"
+	fi
+
+	if [ $days -gt 0 ]; then
+		day_str="day"
+		if [ $days -gt 1 ]; then
+			day_str="days"
+		fi
+		if [ -n "$result" ]; then
+			result="$result and"
+		fi
+		result="$result $days $day_str"
+	fi
+
+	if [ $hours -gt 0 ]; then
+		hour_str="hour"
+		if [ $hours -gt 1 ]; then
+			hour_str="hours"
+		fi
+		if [ -n "$result" ]; then
+			result="$result and"
+		fi
+		result="$result $hours $hour_str"
+	fi
+
+	if [ $minutes -gt 0 ]; then
+		minute_str="minute"
+		if [ $minutes -gt 1 ]; then
+			minute_str="minutes"
+		fi
+		if [ -n "$result" ]; then
+			result="$result and"
+		fi
+		result="$result $minutes $minute_str"
+	fi
+
+	if [ -n "$result" ]; then
+		result="in about $result"
+		echo "$result"
+	fi
 }
 
 #SBATCH --signal=B:USR1@200
@@ -76,10 +169,10 @@ function red_text {
 }
 
 function calltracer () {
-	yellow_text "Git status hash:"
-	git rev-parse HEAD
-        red_text 'Error occured in file/line:'
-        caller
+	LINE_AND_FUNCTION=$(caller)
+	if [[ "$LINE_AND_FUNCTION" != *"./omniopt"* ]] && [[ "$LINE_AND_FUNCTION" != *"./.tests/main_tests"* ]];  then
+		red_text "Error occured in file/line: $LINE_AND_FUNCTION"
+	fi
 
 	echo "Runtime: $(displaytime $SECONDS)"
 	tput bel
@@ -471,9 +564,14 @@ if [[ $tests -eq 0 ]]; then
 fi
 
 if [[ "$continue_previous_job" != "" ]]; then
+	if [[ ! -d "$continue_previous_job" ]]; then
+		echo "The folder $continue_previous_job was not found"
+		exit 105
+	fi
+
 	if [[ -z "$mem_gb" ]]; then
-		if [[ -e "$continue_previous_job/mem_gb" ]]; then
-			mem_gb=$(cat "$continue_previous_job/mem_gb")
+		if [[ -e "$continue_previous_job/state_files/mem_gb" ]]; then
+			mem_gb=$(cat "$continue_previous_job/state_files/mem_gb")
 		else
 			echo "mem_gb could not be determined from previous run or --mem_gb"
 			exit 105
@@ -481,8 +579,8 @@ if [[ "$continue_previous_job" != "" ]]; then
 	fi
 
 	if [[ -z "$gpus" ]]; then
-		if [[ -e "$continue_previous_job/gpus" ]]; then
-			gpus=$(cat "$continue_previous_job/gpus")
+		if [[ -e "$continue_previous_job/state_files/gpus" ]]; then
+			gpus=$(cat "$continue_previous_job/state_files/gpus")
 		else
 			echo "gpus could not be determined from previous run or --gpus"
 			exit 105
@@ -490,8 +588,8 @@ if [[ "$continue_previous_job" != "" ]]; then
 	fi
 
 	if [[ -z "$time" ]]; then
-		if [[ -e "$continue_previous_job/time" ]]; then
-			time=$(cat "$continue_previous_job/time")
+		if [[ -e "$continue_previous_job/state_files/time" ]]; then
+			time=$(cat "$continue_previous_job/state_files/time")
 		else
 			echo "Time could not be determined from previous run or --time"
 			exit 105
@@ -591,7 +689,7 @@ if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
 	fi
 
 	if [[ ! -z $SLURM_JOB_ID ]]; then
-		echo -e "To cancel, use '\e[31mscancel $SLURM_JOB_ID\e[0m'"
+		echo -e "To cancel, press \033[1mCTRL\e[0m \033[1mc\e[0m, then run '\e[31mscancel $SLURM_JOB_ID\e[0m'"
 	fi
 
 	IFS=$' '
@@ -603,14 +701,13 @@ if [ -n "${SLURM_JOB_ID:-}" ] || ! command -v sbatch >/dev/null; then
 	set +e
 	python3 $SCRIPT_DIR/.omniopt.py $args_string &
 	python_pid=$!
+
+	set +x
 	wait $python_pid
+
 	EXIT_CODE=$?
 
 	set -e
-
-	if [[ "$EXIT_CODE" -ne "0" ]]; then
-		echo "Exiting with exit-code $EXIT_CODE"
-	fi
 
 	tput bel
 
@@ -624,10 +721,10 @@ else
 	exit_code=""
 
 	if [[ $gpus -ne 0 ]]; then
-		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB --gres=gpu:$gpus $SCRIPT_DIR/omniopt $args_string | tee /dev/stderr)
+		sbatch_result=$(sbatch -N 1 --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB --gres=gpu:$gpus $SCRIPT_DIR/omniopt $args_string | tee /dev/stderr)
 		exit_code=$?
 	else
-		sbatch_result=$(sbatch --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB $SCRIPT_DIR/omniopt $args_string | tee /dev/stderr)
+		sbatch_result=$(sbatch -N 1 --job-name "$experiment_name" --time=$formatted_time --mem=${mem_gb}GB $SCRIPT_DIR/omniopt $args_string | tee /dev/stderr)
 		exit_code=$?
 	fi
 
@@ -645,12 +742,57 @@ else
 
 				set +x
 
-				echo -n "Waiting until the path $LOG_PATH exists. CTRL-c does NOT cancel the optimization, only the tail...  "
+				last_why_pending_time=$(date +%s)
+
+				estimated_start_time=""
+				estimated_start_time_original=""
+				in_about_time=""
+				_remaining_time=""
+				last_print_line_length=0
 
 				while ! [[ -e $LOG_PATH ]]; do
+					current_time=$(date +%s)
+
+					time_diff=$(($current_time - $last_why_pending_time))
+
+					set +e
+					if command -v whypending 2>/dev/null > /dev/null && [[ $time_diff -gt 10 ]]; then
+						estimated_start_time_original=$(timeout 5 whypending $started_job_nr 2>&1 | grep "Estimated" | sed -e 's#.*time:\s*###' -e 's#^\s*##')
+
+						last_why_pending_time=$current_time
+						if [[ ! -z $estimated_start_time_original ]] && [[ "$estimated_start_time_original" != *"Unknown"* ]]; then
+							estimated_start_time=". Estimated start:$estimated_start_time_original"
+							if [[ ! -z $estimated_start_time_original ]]; then
+								_remaining_time=""
+								_remaining_time=$(remaining_time "$estimated_start_time_original" | sed -e 's#\s\s*# #g')
+
+								if [[ ! -z $_remaining_time ]]; then
+									estimated_start_time="$estimated_start_time ($_remaining_time)"
+								fi
+							fi
+						fi
+					fi
+					set -e
+
 					for i in "${spin[@]}"; do
-						echo -ne "\b$i"
+						print_line="Waiting for \e[4mtail -f $LOG_PATH\e[0m$estimated_start_time... "
+						print_line_length=$(echo "$print_line" | wc -c)
+
+						#backspaces=""
+
+						#for k in $(seq 0 $(($print_line_length + 1000))); do
+						#	backspaces="$backspaces\r"
+						#done
+
+						print_line="$print_line$i"
+						tput cr   # Move cursor to beginning of line
+						tput el   # Delete line from start to finish
+
+						#echo -ne "$backspaces"
+						echo -ne "$print_line"
 						sleep 0.1
+
+						last_print_line_length=$print_line_length
 					done
 				done
 
@@ -722,4 +864,10 @@ else
 fi
 
 echo "Runtime: $(displaytime $SECONDS)"
-exit $exit_code
+
+if [[ "$exit_code" =~ ^[0-9]+$ ]]; then
+	exit $exit_code
+else
+	echo "Invalid exit-code $exit_code detected!"
+	exit 0
+fi
diff --git a/omniopt_evaluate b/omniopt_evaluate
--- a/omniopt_evaluate
+++ b/omniopt_evaluate
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+
 cd $(pwd)
 
 mkdir -p debuglogs
@@ -25,7 +27,6 @@ export HIDEMAXVALUESINPLOT=0
 export ASKEDTOUPGRADE=0
 export DISPLAYGAUGE=1
 export SCIENTIFICNOTATION=4
-export OO_RESULT_COLUMN_NAME=result
 export DEBUG=0
 export LOAD_MODULES=1
 export UPGRADE=1
@@ -173,7 +174,7 @@ function list_option_for_job {
 	eval `resize`
 
 	THISPROJECTDIR="$PROJECTDIR/$PROJECT/"
-	THISPDCSV="$THISPROJECTDIR/$NUMBER/pd.csv"
+	THISPDCSV="$THISPROJECTDIR/$NUMBER/results.csv"
 	THISMAINCSV="$THISPROJECTDIR/$NUMBER/0.csv"
 
 	args=()
@@ -306,21 +307,19 @@ close $fh;
 			list_option_for_job $PROJECT $NUMBER
 
 		elif [[ "$WHATTODO" =~ "plot)" ]]; then
-			if [[ -e "$PROJECTDIR/$PROJECT/$NUMBER/pd.csv" ]]; then
-				set +e
-				OUTPUT=$(./omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/)
+			if [[ -e "$PROJECTDIR/$PROJECT/$NUMBER/results.csv" ]]; then
+				bash $SCRIPT_DIR/omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/
 				if [[ $? -ne 0 ]]; then
 					error_message "$OUTPUT"
 				fi
-				set -e
 			else
 				eval `resize`
-				whiptail --title "No runs" --msgbox "The file '$PROJECTDIR/$PROJECT/$NUMBER/pd.csv' does not exist. This means the job has not yet ran. Cannot create graph from empty job. (Line $LINENO)" $LINES $COLUMNS $(( $LINES - 8 ))
+				whiptail --title "No runs" --msgbox "The file '$PROJECTDIR/$PROJECT/$NUMBER/results.csv' does not exist. This means the job has not yet ran. Cannot create graph from empty job. (Line $LINENO)" $LINES $COLUMNS $(( $LINES - 8 ))
 			fi
 			list_option_for_job $PROJECT $NUMBER
 
 		elif [[ "$WHATTODO" =~ "P)" ]]; then
-			if [[ -e "$PROJECTDIR/$PROJECT/$NUMBER/pd.csv" ]]; then
+			if [[ -e "$PROJECTDIR/$PROJECT/$NUMBER/results.csv" ]]; then
 				minvalue=$(inputbox "Minimum value for plot" "Enter a Minimum value for plotting $PROJECT/$NUMBER (float), leave empty for no Minimum value" "")
 				maxvalue=$(inputbox "Maximum value for plot" "Enter a Maximum value for plotting $PROJECT/$NUMBER (float), leave empty for no Maximum value" "")
 
@@ -356,14 +355,14 @@ close $fh;
 				if [[ -z "$minvalue" ]]; then
 					if [[ -z "$maxvalue" ]]; then
 						set +e
-						./omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/
+						bash $SCRIPT_DIR/omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/
 						if [[ $? -ne 0 ]]; then
 							error_message "$OUTPUT"
 						fi
 						set -e
 					else
 						set +e
-						./omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/ --max $maxvalue
+						bash $SCRIPT_DIR/omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/ --max $maxvalue
 						if [[ $? -ne 0 ]]; then
 							error_message "$OUTPUT"
 						fi
@@ -372,14 +371,14 @@ close $fh;
 				else
 					if [[ -z "$maxvalue" ]]; then
 						set +e
-						./omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/ --min $minvalue
+						bash $SCRIPT_DIR/omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/ --min $minvalue
 						if [[ $? -ne 0 ]]; then
 							error_message "$OUTPUT"
 						fi
 						set -e
 					else
 						set +e
-						./omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/ --min $minvalue --max $maxvalue
+						bash $SCRIPT_DIR/omniopt_plot --run_dir $PROJECTDIR/$PROJECT/$NUMBER/ --min $minvalue --max $maxvalue
 						if [[ $? -ne 0 ]]; then
 							error_message "$OUTPUT"
 						fi
@@ -431,6 +430,12 @@ while (my $line = <$fh>) {
 close $fh;
 			' "$input_file" | egrep -v '^\s*0\s*$' | wc -l)
 
+			exit_code=$?
+			if [[ $exit_code -ne 0 ]]; then
+				echo "inline python script failed"
+				exit $exit_code
+			fi
+
 			FAILED_JOBS_STRING="Number of failed Jobs: $FAILED_JOBS"
 
 			GENERAL_INFO="$NUMBEROFJOBS\n$FAILED_JOBS_STRING\n$WALLCLOCK_TIME"
@@ -456,7 +461,24 @@ close $fh;
 
 function change_variables {
 	eval `resize`
-	MENU_CHOICE=$(whiptail --title "Change variables" --menu "Choose an option" $LINES $COLUMNS $(( $LINES - 8 )) "NONZERODIGITS" "Max. number of non-zero decimal places in the graph plot (currently $NONZERODIGITS)" "SHOWFAILEDJOBSINPLOT" "Show failed runs in plots with really high values (currently $SHOWFAILEDJOBSINPLOT)" "BUBBLESIZEINPX" "Size of bubbles in the plot graph (currently $BUBBLESIZEINPX)" "SVGEXPORTSIZE" "Size of the exported SVG-Graphs of Plot and GPU-Plot (currently $SVGEXPORTSIZE)" "HIDEMAXVALUESINPLOT" "Hide max values in Plot (currently $HIDEMAXVALUESINPLOT)" "DISPLAYGAUGE" "Display gauge when possible (currently $DISPLAYGAUGE)" "PROJECTDIR" "The path where projects are (currently $PROJECTDIR)" "DEBUG" "Debug evaluate-run (currently $DEBUG)" "OO_RESULT_COLUMN_NAME" "The name of the result column in scatter plots (default: result, currently: $OO_RESULT_COLUMN_NAME)" "SCIENTIFICNOTATION" "Use scientific notation and with how many decimal places (currently $SCIENTIFICNOTATION)" "s)" "Save current settings as default for this OmniOpt-installation" "S)" "Save current settings as default for all OmniOpt-installations on your account" "m)" "Main menu" 3>&1 1>&2 2>&3)
+	MENU_CHOICE=$(whiptail \
+		--title "Change variables" \
+		--menu "Choose an option" \
+		$LINES $COLUMNS $(( $LINES - 8 )) \
+		"NONZERODIGITS" "Max. number of non-zero decimal places in the graph plot (currently $NONZERODIGITS)" \
+		"SHOWFAILEDJOBSINPLOT" "Show failed runs in plots with really high values (currently $SHOWFAILEDJOBSINPLOT)" \
+		"BUBBLESIZEINPX" "Size of bubbles in the plot graph (currently $BUBBLESIZEINPX)" \
+		"SVGEXPORTSIZE" "Size of the exported SVG-Graphs of Plot and GPU-Plot (currently $SVGEXPORTSIZE)" \
+		"HIDEMAXVALUESINPLOT" "Hide max values in Plot (currently $HIDEMAXVALUESINPLOT)" \
+		"DISPLAYGAUGE" "Display gauge when possible (currently $DISPLAYGAUGE)" \
+		"PROJECTDIR" "The path where projects are (currently $PROJECTDIR)" \
+		"DEBUG" "Debug evaluate-run (currently $DEBUG)" \
+		"SCIENTIFICNOTATION" "Use scientific notation and with how many decimal places (currently $SCIENTIFICNOTATION)" \
+		"s)" "Save current settings as default for this OmniOpt-installation" \
+		"S)" "Save current settings as default for all OmniOpt-installations on your account" \
+		"m)" "Main menu" \
+		3>&1 1>&2 2>&3
+	)
 	exitstatus=$?
 	if [[ $exitstatus == 0 ]]; then
 		if [[ "$MENU_CHOICE" =~ "m)" ]]; then
@@ -506,10 +528,6 @@ function change_variables {
 				export HIDEMAXVALUESINPLOT=0
 			fi
 
-			change_variables
-		elif [[ "$MENU_CHOICE" =~ "OO_RESULT_COLUMN_NAME" ]]; then
-			chosenvar=$(whiptail --inputbox "Name of the default result-column for plots (default: result)" 8 80 "$OO_RESULT_COLUMN_NAME" --title "OO_RESULT_COLUMN_NAME" 3>&1 1>&2 2>&3)
-			eval "export $MENU_CHOICE=$chosenvar"
 			change_variables
 		elif [[ "$MENU_CHOICE" =~ "SCIENTIFICNOTATION" ]]; then
 			chosenvar=$(whiptail --inputbox "Use scientific notation? 0 = no, 1 = yes with 1 decimal point, 2 = yes with 2 decimal points, ..." 8 80 "$SCIENTIFICNOTATION" --title "SCIENTIFICNOTATION" 3>&1 1>&2 2>&3)
@@ -567,7 +585,6 @@ function change_variables {
 			echo "export PROJECTDIR=$PROJECTDIR" >> .oax_default_settings
 			echo "export DEBUG=$DEBUG" >> .oax_default_settings
 			echo "export SCIENTIFICNOTATION=$SCIENTIFICNOTATION" >> .oax_default_settings
-			echo "export OO_RESULT_COLUMN_NAME=$OO_RESULT_COLUMN_NAME" >> .oax_default_settings
 		elif [[ "$MENU_CHOICE" =~ "S)" ]]; then
 			if [[ -e "$HOME/.oax_default_settings" ]]; then
 				rm ~/.oax_default_settings
@@ -582,7 +599,6 @@ function change_variables {
 			echo "export PROJECTDIR=$PROJECTDIR" >> ~/.oax_default_settings
 			echo "export DEBUG=$DEBUG" >> ~/.oax_default_settings
 			echo "export SCIENTIFICNOTATION=$SCIENTIFICNOTATION" >> ~/.oax_default_settings
-			echo "export OO_RESULT_COLUMN_NAME=$OO_RESULT_COLUMN_NAME" >> ~/.oax_default_settings
 		else
 			eval `resize`
 			whiptail --title "Invalid option" --msgbox "The option '$MENU_CHOICE' is not valid. Returning to the main menu" $LINES $COLUMNS $(( $LINES - 8 )) 3>&1 1>&2 2>&3
@@ -642,7 +658,7 @@ function chose_project_number {
 }
 
 function list_projects {
-	AVAILABLE_PROJECTS=$(ls $PROJECTDIR/*/*/pd.csv 2>/dev/null | sed -e "s#${PROJECTDIR}/##" | sed -e 's#/[0-9]*/pd.csv##' | perl -le 'while (<>) { chomp; chomp; print qq#$_ $_# }' | uniq)
+	AVAILABLE_PROJECTS=$(ls $PROJECTDIR/*/*/results.csv 2>/dev/null | sed -e "s#${PROJECTDIR}/##" | sed -e 's#/[0-9]*/results.csv##' | perl -le 'while (<>) { chomp; chomp; print qq#$_ $_# }' | uniq)
 
 	if [[ -z "$AVAILABLE_PROJECTS" ]]; then
 		echo_red "No projects found (list_projects)"
@@ -747,7 +763,7 @@ if [[ $sourced == "0" ]]; then
 			eval `resize`
 			if (whiptail --title "There is a new version of OmniOpt available" --yesno "Do you want to upgrade?" $LINES $COLUMNS $(( $LINES - 8 ))); then
 			    git pull
-			    bash ./evaluate-run --dont_load_modules --no_upgrade $@
+			    bash $SCRIPT_DIR/evaluate-run --dont_load_modules --no_upgrade $@
 			    exit
 			else
 			    eval `resize`
@@ -772,14 +788,14 @@ if [[ $sourced == "0" ]]; then
         set +x
         (
 		for this_module in ${modules_to_load[*]}; do
-		let load_percent=$load_percent+$stepsize
-		echo "XXX"
-		echo $load_percent
-		echo "Loading modules... ($this_module...)"
-		echo "XXX"
-		if ! myml is-loaded $this_module; then
-			ml $this_module 2>/dev/null
-		fi
+			let load_percent=$load_percent+$stepsize
+			echo "XXX"
+			echo $load_percent
+			echo "Loading modules... ($this_module...)"
+			echo "XXX"
+			if ! myml is-loaded $this_module; then
+				ml $this_module 2>/dev/null
+			fi
 		done
         ) | whiptail --title "Loading Modules" --gauge "Loading modules..." 6 70 0
 
diff --git a/omniopt_plot b/omniopt_plot
--- a/omniopt_plot
+++ b/omniopt_plot
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if [[ ! -z $PRINT_SEPERATOR ]]; then # for tests, so that things are properly visually seperated
+	echo ""
+	echo "========================================================================"
+	echo ""
+fi
+
 _save_to_file=0
 
 function inputbox {
@@ -70,10 +76,10 @@ function displaytime {
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 export ORIGINAL_PWD=$(pwd)
 
-expected_plot_types=("default")
+expected_plot_types=("menu")
 whiptail_args=()
 
-for possible_plot_type in $(ls $SCRIPT_DIR/.omniopt_plot_*.py | sed -e 's#\.py##' -e 's#.*_plot_##'); do
+for possible_plot_type in $(ls $SCRIPT_DIR/.omniopt_plot_*.py | sed -e 's#\.py##' -e 's#.*_plot_##' | tac); do
 	expected_plot_types+=("$possible_plot_type")
 done
 
@@ -89,106 +95,137 @@ set -e
 set -o pipefail
 
 function calltracer () {
-        echo 'Last file/last line:'
-        caller
+	if [[ -z $NO_RUNTIME ]]; then
+		echo 'Last file/last line:'
+		caller
 
-	echo "Runtime: $(displaytime $SECONDS)"
+		echo "Runtime: $(displaytime $SECONDS)"
+	fi
 }
+
 trap 'calltracer' ERR
 
-plot_type="default"
+plot_type="menu"
 min=
 max=
 run_dir=""
 help=0
 
-args=($*)
+args=("$@")
 k=0
+
 while [ $k -lt ${#args[@]} ]; do
-	arg="${args[k]}"
+    arg="${args[k]}"
 
-        case $arg in
-		--run_dir=*)
-			run_dir="${arg#*=}"
-			shift
-			;;
+    case $arg in
+        --run_dir=*)
+            run_dir="${arg#*=}"
+            shift
+            ;;
 
-		--run_dir)
-			k=$((k+1))
+        --run_dir)
+            k=$((k+1))
+            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+                echo "Error: --run_dir requires a value"
+                exit 1
+            fi
+            run_dir="${args[k]}"
+            shift
+            shift
+            ;;
 
-			run_dir="${args[k]}"
+        --save_to_file=*)
+            _save_to_file="${arg#*=}"
+            shift
+            ;;
 
-			shift
-			shift
-			;;
+        --save_to_file)
+            k=$((k+1))
+            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+                echo "Error: --save_to_file requires a value"
+                exit 1
+            fi
+            _save_to_file="${args[k]}"
+            shift
+            shift
+            ;;
 
+        --min=*)
+            min="${arg#*=}"
+            shift
+            ;;
 
+        --min)
+            k=$((k+1))
+            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+                echo "Error: --min requires a value"
+                exit 1
+            fi
+            min="${args[k]}"
+            shift
+            shift
+            ;;
 
-		--min=*)
-			min="${arg#*=}"
-			shift
-			;;
-		--min)
-			k=$((k+1))
+        --max=*)
+            max="${arg#*=}"
+            shift
+            ;;
 
-			min="${args[k]}"
-			shift
-			;;
-		--max=*)
-			max="${arg#*=}"
-			shift
-			;;
-		--max)
-			k=$((k+1))
+        --max)
+            k=$((k+1))
+            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+                echo "Error: --max requires a value"
+                exit 1
+            fi
+            max="${args[k]}"
+            shift
+            shift
+            ;;
 
-			max="${args[k]}"
-			shift
-			;;
-		--plot_type=*)
-			plot_type="${arg#*=}"
-			shift
-			;;
-		--plot_type)
-			k=$((k+1))
+        --plot_type=*)
+            plot_type="${arg#*=}"
+            shift
+            ;;
 
-			plot_type="${args[k]}"
-			shift
-			;;
-                --help|-h)
-			help=1
-			shift
-                        ;;
-                --debug)
-                        set -x
-                        ;;
-        esac
-	k=$((k+1))
+        --plot_type)
+            k=$((k+1))
+            if [ $k -ge ${#args[@]} ] || [[ "${args[k]}" == --* ]]; then
+                echo "Error: --plot_type requires a value"
+                exit 1
+            fi
+            plot_type="${args[k]}"
+            shift
+            shift
+            ;;
+
+        --help|-h)
+            help=1
+            shift
+            ;;
+
+        --debug)
+            set -x
+            shift
+            ;;
+    esac
+    k=$((k+1))
 done
 
 if [[ ! " ${expected_plot_types[@]} " =~ " $plot_type " ]]; then
-    echo "Wrong plot type: $plot_type, but got $plot_type"
+	# Verbinden Sie die Elemente des Arrays zu einem mit "," getrennten String
+	joined_plot_types=$(printf "%s, " "${expected_plot_types[@]}")
+
+	# Entfernen Sie das letzte "," vom gejointen String
+	joined_plot_types=${joined_plot_types%, }
+
+	echo "Invalid plot type $plot_type, valid plot types: $joined_plot_types"
+	exit 99
 fi
 
-if [[ "$plot_type" == "default" ]]; then
-	if [[ "$run_dir" == "" ]]; then
-		echo "--run_dir is missing"
-		exit 1
-	fi
-
-	if [[ -f "$run_dir" ]]; then
-		echo "--run_dir is a file"
-		exit 1
-	fi
-
-	if [[ ! -d "$run_dir" ]]; then
-		echo "--run_dir is not a directory"
-		exit 1
-	fi
-
-	eval `resize`
-
+function menu {
+	whiptail_args=()
 	for possible_plot_type in "${expected_plot_types[@]}"; do
-		if [[ "$possible_plot_type" == "default" ]]; then
+		if [[ "$possible_plot_type" == "menu" ]]; then
 			continue
 		fi
 
@@ -226,7 +263,7 @@ if [[ "$plot_type" == "default" ]]; then
 	done
 
 	if [ ${#whiptail_args[@]} -eq 0 ]; then
-		echo "It seems like the run folder does not have any plottable data."
+		echo "It seems like the run folder $run_dir does not have any plottable data."
 		exit 3
 	fi
 
@@ -253,13 +290,14 @@ if [[ "$plot_type" == "default" ]]; then
 		minmaxstring=" (min: $min, max: $max)"
 	fi
 
+	eval `resize`
 	WHATTODO=$(whiptail \
 		--title "Available options for $run_dir" \
 		--menu \
 		"Chose what plot to open:" \
 		$LINES $COLUMNS $(( $LINES - 8 )) \
-		"minmax)" "set min/max values$minmaxstring" \
 		"${whiptail_args[@]}" \
+		"minmax)" "set min/max values$minmaxstring" \
 		"q)" "quit" 3>&1 1>&2 2>&3
 	)
 
@@ -294,10 +332,12 @@ if [[ "$plot_type" == "default" ]]; then
 	plot_type=$WHATTODO
 	if [[ "$plot_type" == *"save_to_file"* ]]; then
 		plot_type=$(echo "$plot_type" | sed -e 's# .*##')
-		_save_to_file=1
+		if [[ "$_save_to_file" -eq "0" ]]; then
+			_save_to_file=1
+		fi
 	fi
 
-	if [[ "$_save_to_file" == "1" ]]; then
+	if [[ "$_save_to_file" != "0" ]]; then
 		_path=$(whiptail --inputbox "Path of the plot?" 8 39 "$run_dir/$plot_type.svg" --title "Choose path" 3>&1 1>&2 2>&3)
 
 		exitstatus=$?
@@ -307,6 +347,25 @@ if [[ "$plot_type" == "default" ]]; then
 			exit 0
 		fi
 	fi
+}
+
+if [[ "$plot_type" == "menu" ]]; then
+	if [[ "$run_dir" == "" ]]; then
+		echo "--run_dir is missing"
+		exit 1
+	fi
+
+	if [[ -f "$run_dir" ]]; then
+		echo "--run_dir is a file"
+		exit 1
+	fi
+
+	if [[ ! -d "$run_dir" ]]; then
+		echo "--run_dir is not a directory"
+		exit 1
+	fi
+
+	menu
 fi
 
 cd $ORIGINAL_PWD
@@ -314,7 +373,7 @@ cd $ORIGINAL_PWD
 source $SCRIPT_DIR/.shellscript_functions
 source $SCRIPT_DIR/.general.sh
 
-if [[ "$plot_type" != "default" ]]; then
+if [[ "$plot_type" != "menu" ]]; then
 	if ! [[ -e "$SCRIPT_DIR/.omniopt_plot_$plot_type.py" ]]; then
 		# Verbinden Sie die Elemente des Arrays zu einem mit "," getrennten String
 		joined_plot_types=$(printf "%s, " "${expected_plot_types[@]}")
@@ -327,29 +386,36 @@ if [[ "$plot_type" != "default" ]]; then
 	fi
 fi
 
-set +ex
+set +e
 if [[ "$_save_to_file" == "0" ]]; then
 	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot_$plot_type.py --run_dir $run_dir $* 2>&1)
 	exit_code=$?
 else
-	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot_$plot_type.py --run_dir $run_dir --save_to_file $_save_to_file $* 2>&1)
+	OUTPUT=$(python3 $SCRIPT_DIR/.omniopt_plot_$plot_type.py --run_dir $run_dir --save_to_file=$_save_to_file $* 2>&1)
 	exit_code=$?
 fi
-set -ex
+set -e
 
 if [[ "$exit_code" -ne "0" ]]; then
 	if command -v whiptail 2>/dev/null >/dev/null; then
 		if [[ -z $NO_WHIPTAIL ]]; then
 			error_message "$OUTPUT"
 		else
-			echo $OUTPUT
+			if [[ ! -z "$OUTPUT" ]]; then
+				echo_red "$OUTPUT"
+			fi
 		fi
 	else
-		echo -- "$OUTPUT"
+		echo_red "$OUTPUT"
 	fi
 else
-	echo "$OUTPUT"
+	if [[ ! -z  "$OUTPUT" ]]; then
+		echo "$OUTPUT"
+	fi
 fi
 
-echo "Runtime: $(displaytime $SECONDS)"
+if [[ -z $NO_RUNTIME ]]; then
+	echo "Runtime: $(displaytime $SECONDS), plot_type: $plot_type, exit-code: $exit_code"
+fi
+
 exit $exit_code
