new version

diff --git a/.tests/start_simple_optimization_run b/.tests/start_simple_optimization_run
--- a/.tests/start_simple_optimization_run
+++ b/.tests/start_simple_optimization_run
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+export OO_MAIN_TESTS=1
+
 int_re='^[+-]?[0-9]+$'
 function echoerr() {
         echo "$@" 1>&2
@@ -36,6 +38,9 @@ function help () {
 	echo "  --num_random_steps=(INT)                           Number of random steps"
 	echo "  --model=STR                                        Model name"
 	echo "  --gridsearch                                       Do gridsearch"
+	echo "  --gpus=(INT)                                       Nr of GPUs per worker"
+	echo "  --time=(INT)                                       Time each subjob should run"
+        echo "  --allow_failure                                    Adds a param to randomly fail"
         echo "  --help                                             this help"
         echo "  --debug                                            Enables debug mode (set -x)"
         exit $1
@@ -56,7 +61,7 @@ max_eval=30
 num_parallel_jobs=20
 allow_failure=0
 num_random_steps=$num_parallel_jobs
-time=20
+time=60
 model=BOTORCH_MODULAR
 
 args=("$@")
@@ -163,6 +168,25 @@ while [ $k -lt ${#args[@]} ]; do
 			fi
 
 			;;
+		--gpus=*)
+			NUM_GPUS="${i#*=}"
+			if ! [[ $NUM_GPUS =~ $int_re ]] ; then
+				red_text "error: --gpus not a INT: $i" >&2
+				exit 100
+			fi
+
+			;;
+		--gpus)
+			shift
+			k=$((k+1))
+
+			NUM_GPUS="${args[k]}"
+			if ! [[ $NUM_GPUS =~ $int_re ]] ; then
+				red_text "error: --gpus not a INT: $i" >&2
+				exit 100
+			fi
+			;;
+
 		--help*)
 			help 1
 			;;
@@ -194,18 +218,14 @@ fi
 
 
 PARTITION="alpha"
-GPUS=0
 TESTNAME=__main__tests__
 
-if [[ "$PARTITION" == "alpha" ]]; then
-	GPUS=1
-fi
 
 if [[ "$gridsearch" -eq "1" ]]; then
 	TESTNAME="${TESTNAME}_gridsearch"
 	if [[ "$allow_failure" -eq "0" ]]; then
 		./omniopt \
-			--show_sixel_graphics \
+			--send_anonymized_usage_stats \
 			--partition=$PARTITION \
 			--experiment_name=$TESTNAME \
 			--mem_gb=5 \
@@ -213,7 +233,7 @@ if [[ "$gridsearch" -eq "1" ]]; then
 			--worker_timeout=5 \
 			--max_eval=$max_eval \
 			--num_parallel_jobs=$num_parallel_jobs \
-			--gpus=$GPUS \
+			--gpus=$NUM_GPUS \
 			--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
 			--parameter int_param range -100 10 int \
 			--parameter float_param range -100 10 float \
@@ -221,12 +241,14 @@ if [[ "$gridsearch" -eq "1" ]]; then
 			--parameter int_param_two range -100 10 int \
 			--follow \
 			--num_random_steps=$num_random_steps \
+			--model=$model \
+			--auto_exclude_defective_hosts \
 			--gridsearch \
 			--hide_ascii_plots
 		exit_code=$?
 	else
 		./omniopt \
-			--show_sixel_graphics \
+			--send_anonymized_usage_stats \
 			--partition=$PARTITION \
 			--experiment_name=$TESTNAME \
 			--mem_gb=5 \
@@ -234,7 +256,7 @@ if [[ "$gridsearch" -eq "1" ]]; then
 			--worker_timeout=5 \
 			--max_eval=$max_eval \
 			--num_parallel_jobs=$num_parallel_jobs \
-			--gpus=$GPUS \
+			--gpus=$NUM_GPUS \
 			--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0) \
 			--parameter int_param range -100 10 int \
 			--parameter float_param range -100 10 float \
@@ -243,6 +265,8 @@ if [[ "$gridsearch" -eq "1" ]]; then
 			--parameter fail_or_not choice "0,1" \
 			--follow \
 			--num_random_steps=$num_random_steps \
+			--model=$model \
+			--auto_exclude_defective_hosts \
 			--gridsearch \
 			--hide_ascii_plots
 		exit_code=$?
@@ -250,7 +274,7 @@ if [[ "$gridsearch" -eq "1" ]]; then
 else
 	if [[ "$allow_failure" -eq "0" ]]; then
 		./omniopt \
-			--show_sixel_graphics \
+			--send_anonymized_usage_stats \
 			--partition=$PARTITION \
 			--experiment_name=$TESTNAME \
 			--mem_gb=5 \
@@ -258,7 +282,7 @@ else
 			--worker_timeout=5 \
 			--max_eval=$max_eval \
 			--num_parallel_jobs=$num_parallel_jobs \
-			--gpus=$GPUS \
+			--gpus=$NUM_GPUS \
 			--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)'" | base64 -w 0) \
 			--parameter int_param range -100 10 int \
 			--parameter float_param range -100 10 float \
@@ -266,11 +290,13 @@ else
 			--parameter int_param_two range -100 10 int \
 			--follow \
 			--num_random_steps=$num_random_steps \
+			--model=$model \
+			--auto_exclude_defective_hosts \
 			--hide_ascii_plots
 		exit_code=$?
 	else
 		./omniopt \
-			--show_sixel_graphics \
+			--send_anonymized_usage_stats \
 			--partition=$PARTITION \
 			--experiment_name=$TESTNAME \
 			--mem_gb=5 \
@@ -278,7 +304,7 @@ else
 			--worker_timeout=5 \
 			--max_eval=$max_eval \
 			--num_parallel_jobs=$num_parallel_jobs \
-			--gpus=$GPUS \
+			--gpus=$NUM_GPUS \
 			--run_program=$(echo -n "./.tests/optimization_example --int_param='%(int_param)' --float_param='%(float_param)' --choice_param='%(choice_param)'  --int_param_two='%(int_param_two)' --fail_or_not=%(fail_or_not)" | base64 -w 0) \
 			--parameter int_param range -100 10 int \
 			--parameter float_param range -100 10 float \
@@ -287,6 +313,8 @@ else
 			--parameter fail_or_not choice "0,1" \
 			--follow \
 			--num_random_steps=$num_random_steps \
+			--model=$model \
+			--auto_exclude_defective_hosts \
 			--hide_ascii_plots
 		exit_code=$?
 	fi
